### PR TITLE
Modified the build to use maven instead of Buildr

### PR DESCRIPTION
**Pull request by douglaspalmer**

### CODE REVIEW

**Comment by tsurdilo** [comment]
Your pull request from what I see completely deletes the existing apache buildr build setup. Sorry I cannot accept this, as was hoping we would have both in place and users can use the one more appropriate to their needs. I would gladly accept the changes to the pom.xml all day.

**Comment by douglaspalmer** [comment]
Sorry Tihomir

Maintaining parallel build systems is a recipe for disaster. Users will inevitably only update their preferred version and the builds will drift out of sync again. 

Regards
Doug

**Comment by tsurdilo** [comment]
I know and the plan is to completely replace the existing stuff with 
yours. Just for now I'd like to maintain both until your changes have 
passed let's say 1 community release :)

Is that OK?

**Comment by krisv** [comment]
Keeping multiple build systems probably isn't the best idea.  I guess it's just fear of removing something that we know works ;)  But we should just make sure the new stuff works as well, by testing the resulting designer war, and/or comparing it with the one created by buildr.  If everything is fine, we can remove remove the buildr stuff and use maven from now on, as we do for the other modules. @tsurdilo can you take care of this?

**Comment by tsurdilo** [comment]
applied. thanks.

**Pull request merged**
