### PR TITLE
BZ832910 - Designer doesn't load on Windows. JSON should be UTF-8

### PR DESCRIPTION
**Pull request by tkobayas**
Making sure bpmn2.0jbpm.json written in UTF-8 so that StencilSetServiceServlet will respond with JSON in UTF-8.

### CODE REVIEW

**Comment by being** [comment]
what's version number of the maven?

**Comment by being** [comment]
Hello,i am a chinese,my English is poor,Can you understand i say ?

**Comment by being** [comment]
There had a saying in my hometown, it's "你刚卓牛B咧！".

**Comment by tkobayas** [comment]
Hi being, I'm not understanding your comments well but jBPM User Forum is the good place for questions/discussion. Please post a question there.
https://community.jboss.org/en/jbpm?view=discussions

Cheers,

**Pull request merged**
